const menu=document.querySelector('.menu'),nav=document.querySelector('.header nav');menu?.addEventListener('click',()=>{nav.classList.toggle('show')});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('show')));


// V7: Portfolio data from the published Google Spreadsheet.
const SHEET_CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRWq5cCMcd3a_kXv0M6dyd_75xh3t5wXjCeQVqnIPpDoNpNO3U63DE7m9Uk4rexQnGIqtYcDFjrbWoO/pub?gid=0&single=true&output=csv';
const portfolioGrid = document.getElementById('portfolioGrid');
const portfolioFilters = document.getElementById('portfolioFilters');
const portfolioStatus = document.getElementById('portfolioStatus');
let portfolioItems = [];
function parseCSV(text){ const rows=[]; let row=[], cell='', quoted=false; for(let i=0;i<text.length;i++){ const c=text[i], n=text[i+1]; if(c==='"' && quoted && n==='"'){cell+='"';i++;continue} if(c==='"'){quoted=!quoted;continue} if(c===','&&!quoted){row.push(cell.trim());cell='';continue} if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell.trim()); if(row.some(v=>v!==''))rows.push(row); row=[];cell='';continue} cell+=c;} if(cell!==''||row.length){row.push(cell.trim());if(row.some(v=>v!==''))rows.push(row)} return rows;}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderFilters(){const cats=['Semua',...new Set(portfolioItems.map(x=>x.kategori).filter(Boolean))];portfolioFilters.innerHTML=cats.map((c,i)=>`<button class="portfolio-filter ${i===0?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');portfolioFilters.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{portfolioFilters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPortfolio(b.dataset.cat)}));}
function renderPortfolio(cat='Semua'){const items=cat==='Semua'?portfolioItems:portfolioItems.filter(x=>x.kategori.toLowerCase()===cat.toLowerCase()); if(!items.length){portfolioGrid.innerHTML='<div class="portfolio-empty">Belum ada dokumentasi pada kategori ini.</div>';return} portfolioGrid.innerHTML=items.map(x=>`<article class="portfolio-card"><div class="portfolio-card-body"><div class="portfolio-card-cat">${esc(x.kategori||'Dokumentasi')}</div><h3>${esc(x.judul)}</h3><p>${esc(x.keterangan||'Dokumentasi pekerjaan PT. Bangun Bangkit Bersama.')}</p><a class="portfolio-drive" href="${esc(x.link)}" target="_blank" rel="noopener">LIHAT DOKUMENTASI ↗</a></div></article>`).join('');}
async function loadPortfolio(){try{const r=await fetch(SHEET_CSV_URL,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const rows=parseCSV(await r.text());const headers=(rows.shift()||[]).map(x=>x.toLowerCase());const idx={judul:headers.indexOf('judul'),kategori:headers.indexOf('kategori'),link:headers.indexOf('link drive'),keterangan:headers.indexOf('keterangan')};portfolioItems=rows.map(r=>({judul:r[idx.judul]||'',kategori:r[idx.kategori]||'Lainnya',link:r[idx.link]||'#',keterangan:r[idx.keterangan]||''})).filter(x=>x.judul&&x.link&&x.link!=='#');if(!portfolioItems.length)throw new Error('Belum ada data portofolio yang terbaca.');renderFilters();renderPortfolio();portfolioStatus.textContent=`${portfolioItems.length} dokumentasi dimuat dari Google Spreadsheet.`;}catch(e){portfolioGrid.innerHTML='<div class="portfolio-error">Data portofolio belum dapat dimuat dari Google Spreadsheet. Pastikan Spreadsheet sudah dipublish ke web dan kolomnya bernama: Judul, Kategori, Link Drive, Keterangan.</div>';portfolioStatus.textContent='';portfolioStatus.classList.add('error');console.warn('Portfolio:',e)}}
if(portfolioGrid)loadPortfolio();
