(() => {
  'use strict';
  const menu=document.querySelector('.menu'), nav=document.querySelector('#site-nav');
  const navLinks=document.querySelectorAll('#site-nav a');
  function closeMenu(){if(!menu||!nav)return;nav.classList.remove('show');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Buka menu navigasi');}
  menu?.addEventListener('click',()=>{const open=nav.classList.toggle('show');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Tutup menu navigasi':'Buka menu navigasi');});
  navLinks.forEach(a=>a.addEventListener('click',closeMenu));
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
  if('IntersectionObserver' in window){const sections=[...document.querySelectorAll('main section[id]')];const io=new IntersectionObserver(entries=>{const v=entries.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!v)return;navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${v.target.id}`));},{rootMargin:'-30% 0px -55% 0px',threshold:[.05,.2,.5]});sections.forEach(s=>io.observe(s));}

  const SHEET_CSV_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vRWq5cCMcd3a_kXv0M6dyd_75xh3t5wXjCeQVqnIPpDoNpNO3U63DE7m9Uk4rexQnGIqtYcDFjrbWoO/pub?gid=0&single=true&output=csv';
  const grid=document.getElementById('portfolioGrid'), filters=document.getElementById('portfolioFilters'), status=document.getElementById('portfolioStatus'); let items=[];
  function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell.trim());cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(v=>v!==''))rows.push(row);row=[];cell='';continue}cell+=c}if(cell!==''||row.length){row.push(cell.trim());if(row.some(v=>v!==''))rows.push(row)}return rows}
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' ');
  function safeURL(value){try{const u=new URL(value,location.href);return u.protocol==='https:'||u.protocol==='http:'}catch{return false}}
  function renderFilters(){const cats=['Semua',...new Set(items.map(x=>x.kategori).filter(Boolean))];filters.innerHTML=cats.map((c,i)=>`<button type="button" class="portfolio-filter ${i===0?'active':''}" data-cat="${esc(c)}" aria-pressed="${i===0}">${esc(c)}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{filters.querySelectorAll('button').forEach(x=>{const a=x===b;x.classList.toggle('active',a);x.setAttribute('aria-pressed',String(a))});renderPortfolio(b.dataset.cat)}))}
  function renderPortfolio(cat='Semua'){const list=cat==='Semua'?items:items.filter(x=>x.kategori.toLowerCase()===cat.toLowerCase());if(!list.length){grid.innerHTML='<div class="portfolio-empty">Belum ada dokumentasi pada kategori ini.</div>';return}grid.innerHTML=list.map(x=>{const link=safeURL(x.link)?x.link:'#';return `<article class="portfolio-card"><div class="portfolio-card-body"><div class="portfolio-card-cat">${esc(x.kategori||'Dokumentasi')}</div><h3>${esc(x.judul)}</h3><p>${esc(x.keterangan||'Dokumentasi pekerjaan PT. Bangun Bangkit Bersama.')}</p><a class="portfolio-drive ${link==='#'?'is-disabled':''}" href="${esc(link)}" ${link==='#'?'aria-disabled="true"':'target="_blank" rel="noopener noreferrer"'}>${link==='#'?'LINK TIDAK TERSEDIA':'LIHAT DOKUMENTASI ↗'}</a></div></article>`}).join('')}
  async function loadPortfolio(){try{const r=await fetch(SHEET_CSV_URL,{cache:'no-store',headers:{Accept:'text/csv'}});if(!r.ok)throw Error('HTTP '+r.status);const rows=parseCSV(await r.text());if(!rows.length)throw Error('Spreadsheet kosong.');const h=rows.shift().map(norm),idx={judul:h.indexOf('judul'),kategori:h.indexOf('kategori'),link:h.indexOf('link drive'),keterangan:h.indexOf('keterangan')};if(idx.judul<0||idx.kategori<0||idx.link<0)throw Error('Kolom wajib tidak ditemukan.');items=rows.map(r=>({judul:r[idx.judul]||'',kategori:r[idx.kategori]||'Lainnya',link:r[idx.link]||'',keterangan:r[idx.keterangan]||''})).filter(x=>x.judul&&safeURL(x.link));if(!items.length)throw Error('Belum ada data portofolio yang valid.');renderFilters();renderPortfolio();status.textContent=`${items.length} dokumentasi dimuat dari Google Spreadsheet.`;status.classList.remove('error')}catch(e){grid.innerHTML='<div class="portfolio-error"><strong>Dokumentasi belum dapat dimuat.</strong><span>Pastikan Spreadsheet sudah dipublish ke web dan memiliki kolom: Judul, Kategori, Link Drive, Keterangan.</span><button type="button" class="portfolio-retry">Coba lagi</button></div>';status.textContent='';status.classList.add('error');grid.querySelector('.portfolio-retry')?.addEventListener('click',loadPortfolio);console.warn('Portfolio:',e)}}
  if(grid)loadPortfolio();
})();
